# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [107]:
# import NUMPY as np
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [108]:
# print numpy version and configuration
print(np.__version__)
print(np.__config__)

1.26.4
<module 'numpy.__config__' from 'c:\\Users\\yogan\\anaconda3\\Lib\\site-packages\\numpy\\__config__.py'>


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [109]:
a = np.random.random((2,3,5))


### 4. Print a.


In [110]:
print(a)

[[[0.47977762 0.21870032 0.86138462 0.30693562 0.03230225]
  [0.61177427 0.72063279 0.86098734 0.79661723 0.29440965]
  [0.76377036 0.76593492 0.48494029 0.55256272 0.30898671]]

 [[0.94740109 0.25534496 0.8381518  0.68626787 0.60123153]
  [0.15260212 0.45568277 0.13150679 0.77010811 0.19790307]
  [0.72615582 0.86203707 0.19279587 0.66015354 0.96821854]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [111]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [112]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [113]:
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [114]:
a+b
#print(a.shape) = (2, 3, 5)
#print(b.shape) = (5, 2, 3) . Both the arrays are diffenent and incompatible for matrix addition


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
#b was (5,2,3) before transpose and the aim is to make it (2,3,5) to match a's shape. 
#So we transpose b by moving axis (0,1,2) to (1,2,0)
c = b.transpose(1,2,0) 
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
#print(a.shape) =(2, 3, 5)
#print(c.shape) = (2, 3, 5). they are now compatible for matrix addition


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print (d) # this shows the result of each element added together

[[[1.0472033  1.49289757 1.16025703 1.48147314 1.17155376]
  [1.0025731  1.5461353  1.2403001  1.82012037 1.22942851]
  [1.493624   1.18238208 1.25802264 1.15597359 1.14024425]]

 [[1.78351958 1.04128565 1.19311521 1.27348797 1.4910492 ]
  [1.72953714 1.25651888 1.26543027 1.68878276 1.90127452]
  [1.83446307 1.03413615 1.51225539 1.93955092 1.74408829]]]



### 12. Multiply a and c. Assign the result to e.


In [ ]:
e =a * c



### 13. Does e equal to a? Why or why not?


In [ ]:
e == a
# True. e and a equal because basically each element of a is being multiplied by c which is all ones

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.939550919320329
1.0025731046687523
1.4036894584606263



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [ ]:
f = np.empty((2, 3, 5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
# f is an empty array of shape (2,3,5)
for i in range(2): # accessing the first outer dimension which has 2 elements
    for j in range(3): # accessing the second dimension which has 3 elements
        for k in range (5): # accessing the third dimension which has 5 elements
            k_value = d[i,j,k] # accessing each element value in d
            if d_mean > k_value > d_min:
               f[i,j,k] = 25
            elif d_max > k_value > d_mean:
                f[i,j,k] = 75
            elif k_value == d_mean:
                f[i,j,k] = 50       
            elif k_value == d_min:
                f[i,j,k] = 0
            elif k_value == d_max:
                f[i,j,k]   = 100   






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print (d)
print (f)


[[[1.0472033  1.49289757 1.16025703 1.48147314 1.17155376]
  [1.0025731  1.5461353  1.2403001  1.82012037 1.22942851]
  [1.493624   1.18238208 1.25802264 1.15597359 1.14024425]]

 [[1.78351958 1.04128565 1.19311521 1.27348797 1.4910492 ]
  [1.72953714 1.25651888 1.26543027 1.68878276 1.90127452]
  [1.83446307 1.03413615 1.51225539 1.93955092 1.74408829]]]
[[[ 25.  75.  25.  75.  25.]
  [  0.  75.  25.  75.  25.]
  [ 75.  25.  25.  25.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  25.  75. 100.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
# f is an empty array of shape (2,3,5)
f = np.empty((2, 3, 5), dtype=str) # specify dtype as string to hold string values
for i in range(2): # accessing the first outer dimension which has 2 elements
    for j in range(3): # accessing the second dimension which has 3 elements
        for k in range (5): # accessing the third dimension which has 5 elements
            k_value = d[i,j,k] # accessing each element value in d
            if d_mean > k_value > d_min:   #checking the given conditions
               f[i,j,k] = 'B'
            elif d_max > k_value > d_mean:
                f[i,j,k] = 'C'
            elif k_value == d_mean:
                f[i,j,k] = 'D'       
            elif k_value == d_min:
                f[i,j,k] = 'A'
            elif k_value == d_max:
                f[i,j,k]   = 'E'

print (d)
print (f)

[[[1.0472033  1.49289757 1.16025703 1.48147314 1.17155376]
  [1.0025731  1.5461353  1.2403001  1.82012037 1.22942851]
  [1.493624   1.18238208 1.25802264 1.15597359 1.14024425]]

 [[1.78351958 1.04128565 1.19311521 1.27348797 1.4910492 ]
  [1.72953714 1.25651888 1.26543027 1.68878276 1.90127452]
  [1.83446307 1.03413615 1.51225539 1.93955092 1.74408829]]]
[[['B' 'C' 'B' 'C' 'B']
  ['A' 'C' 'B' 'C' 'B']
  ['C' 'B' 'B' 'B' 'B']]

 [['C' 'B' 'B' 'B' 'C']
  ['C' 'B' 'B' 'C' 'C']
  ['C' 'B' 'C' 'E' 'C']]]
